### ISSUE TITLE
Attach APK to latest release?

### ISSUE THREAD

**Issue by IzzySoft** [samueltardieu/harassme#4]
Could you please add the APK to the last release? And btw, is it really the last then – as I saw your app is unlisted from Playstore?

**Comment by IzzySoft** [comment]
@samueltardieu do you still maintain this app?

**Comment by samueltardieu** [comment]
Nope.

**Comment by IzzySoft** [comment]
OK, thanks. Sad but at least clear now.

**Comment by IzzySoft** [comment]
PS: You might consider archiving the repo to make the status clear (can be unarchived at any time if needed).

**Comment by samueltardieu** [comment]
I'll add a note to the README instead.

**Comment by IzzySoft** [comment]
Good idea :smile: Actually, you could do both (for those who "TL;DR", the "yellow bar" is more obvious) – but that's of course up to you. Thanks again!
